### ISSUE TITLE
Support for Python 3.11?

### ISSUE THREAD

**Issue by dsudar** [vanvalenlab/deepcell-toolbox#145] opened 2024-03-12 21:27 UTC
The documentation only indicates support up to Python 3.10. Before I go down the dependencies rabbit hole, has anyone successfully used deepcell/mesmer prediction under Python 3.11?

**Comment by rossbar** [comment] 2024-03-14 02:09
I'll go ahead and close this as a duplicate of vanvalenlab/deepcell-tf#711 -- the same response there applies here, more or less. Updating to latest Python would be much simpler for this package since there is no explicit tensorflow dependency, but these utility functions don't make much sense outside the context of the main deepcell-tf package.

If deepcell-tf were to be updated, this and related packages like vanvalenlab/deepcell-spots would certainly get the same treatment!

**Closed as completed by rossbar** 2024-03-14 02:09 UTC
